### ISSUE TITLE
Could not write to file 'D:\android\xx\module-aaa\build\poms\pom-default.xml'.

### ISSUE THREAD

**Issue by Aarthas** [yjfnypeu/Speedup#2]
有些module报错如下
Could not write to file 'D:\android\xx\module-aaa\build\poms\pom-default.xml'.
有些module是可以的

**Comment by Aarthas** [comment]
发现是同时配了
implementation project(path: ':bbb')
api project(path: ':bbb')
就不成功了
删掉一个就可以了

**Comment by yjfnypeu** [comment]
你这是啥。。。完全看不懂。。。最好能提供一份会出问题的demo。
